name: macos-x64

on: [pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install requirements
      run : brew install gmp clang-format@11
    - name: Initialize submodule
      run : git submodule update --init --recursive
    - name: Build bls
      run: |
        cd bls
        mkdir build
        cd build
        cmake ../ -DBLS_ETH=1
        sudo make -j4
    - name: Build bls csharp binding
      run: |
        cd bls/ffi/cs
        dotnet restore bls.sln
        dotnet build bls_eth.csproj --configuration Release --no-restore
    - name: Replace CSbls binary
      run: |
        rm BLSWrapper/bls.dll
        cd bls
        cp ./bin/netstandard2.0/bls.dll ../BLSWrapper/bls.dll
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Copy native bls library
      run : |
        cp ./bls/build/lib/libbls384_256.*.dylib ./BLSWrapper.Tests/bin/Release/net6.0/libbls384_256.dylib
    - name: Test
      run: |
        export LD_LIBRARY_PATH=/home/runner/work/BLSWrapper/BLSWrapper/
        dotnet test --configuration Release --no-build --verbosity normal
