name: csbinding-build-and-test

on: [pull_request]

jobs:
  # TODO: Add Apple Silicon tests.
  # https://github.com/github/roadmap/issues/507

  linux-x64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        cd ffi/cs
        dotnet restore bls.sln
    - name: Build
      run: |
        cd ffi/cs
        dotnet build bls.sln --configuration Release --no-restore
    - name: Test
      run: |
        cd ffi/cs
        dotnet test bls.sln --configuration Release --no-build --verbosity normal

  windows-x64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        cd ffi/cs
        dotnet restore bls.sln
    - name: Build
      run: |
        cd ffi/cs
        dotnet build bls.sln --configuration Release --no-restore
    - name: Test
      run: |
        cd ffi/cs
        dotnet test bls.sln --configuration Release --no-build --verbosity normal

  osx-x64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        cd ffi/cs
        dotnet restore bls.sln
    - name: Build
      run: |
        cd ffi/cs
        dotnet build bls.sln --configuration Release --no-restore
    - name: Test
      run: |
        cd ffi/cs
        dotnet test bls.sln --configuration Release --no-build --verbosity normal
